export const roadmapItems = [
  {
    id: 'admin-console',
    title: 'Admin Console',
    category: 'Game Modes',
    column: 'gameModes',
    status: 'inProgress',
    communitySignal: 'High curiosity',
    dependsOn: [],
    description: 'Enable user to create anything in the game immediately without prerequisites or other restrictions.',
    details: 'Multi-functional mode that enables instant creation, tracking player progress, creating scenarios, and testing of game systems. This mode is intended for educators, parents, and curious players.',
  },
  {
    id: 'multiplayer',
    title: 'Multiplayer',
    category: 'Game Modes',
    column: 'gameModes',
    status: 'planned',
    communitySignal: 'Core',
    dependsOn: [],
    description: 'Co-op and competitive multiplayer modes for players to explore, build, and learn together.',
    details: 'Co-operative play completely reshapes the experience in highly memorable ways. High priority game feature.',
  },
  {
    id: 'receptors',
    title: 'Receptors',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'planned',
    communitySignal: 'Core',
    dependsOn: [],
    description: 'Cells can directly communicate. Implement the idea in the game.',
    details: 'Cell-cell communication is a fundamental aspect of biological systems. Implementing this in the game will allow players to interact with and influence each other\'s actions, more complex interactions with the environment, and lead to even more emergent behavior.',
  },
  {
    id: 'motility',
    title: 'Motility',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'planned',
    communitySignal: 'Needs testing',
    dependsOn: ['cytoskeleton'],
    description: 'Cells can move!',
    details: 'Flagella would be the primary new idea introduced here.',
  },
  {
    id: 'predation',
    title: 'Predation',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'exploring',
    communitySignal: 'Needs testing',
    dependsOn: ['motility', 'enzymes'],
    description: 'Cells can eat other cells.',
    details: 'A cell could completely engulf another cell, break it down into constituent components, and use all of those raw materials itself. It would take a lot of energy and the chances of consuming other cells are not 100%, but the payoff could be big.',
  },
  {
    id: 'enzymes',
    title: 'Enzymes',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'planned',
    communitySignal: 'Core',
    dependsOn: ['proteins'],
    description: 'Introduce the concept of enzymes into the game.',
    details: 'The buildling blocks all exist in the game, and enzymes are a fundamental concepts, but the concept of enzymes does not explicitly exist (it does implicitly). There are many places in which this idea could be implemented.',
  },
  {
    id: 'ph',
    title: 'Acidity',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'exploring',
    communitySignal: 'Core',
    dependsOn: [],
    description: 'Acidity might be another dimension of control in the game.',
    details: 'As in real cells, a pH gradient can be established in a cell to control the folding of its proteins. Not too difficult to implement and big impact in terms of both game mechanics and educational value, but needs to be done thoughtfully.',
  },
  {
    id: 'community-sandbox',
    title: 'Community Sandbox',
    category: 'Game Modes',
    column: 'gameModes',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: [],
    description: 'Players can collaborate on large trial-and-error projects.',
    details: 'This is a way of bringing the community into cell simulations. Would things actually work in this way? Test ideas with no fear of being right or wrong. Each person contributes ideas and resources. An AI-curated idea portal and periodic challenges.',
  },
  {
    id: 'scenario-designer',
    title: 'Scenario Designer',
    category: 'Game Modes',
    column: 'gameModes',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: [],
    description: 'Players can author their own scenarios.',
    details: 'Educators (or anyone) can develop content using in game assets without any coding to make their own scenarios, like a level editor.',
  },
  {
    id: 'marketplace',
    title: 'Exchange Marketplace',
    category: 'Foundations',
    column: 'foundations',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: [],
    description: 'Players can exchange their creations.',
    details: 'Content creations can be shared with the world. Those that are particularly useful for teaching, for example, may be highly in demand.',
  },
  {
    id: 'ph-visor',
    title: 'pH Visor',
    category: 'Foundations',
    column: 'foundations',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: [],
    description: 'Players can see the world in terms of its acidity.',
    details: 'Like the hydrophobicity visor, this translates a fundamental concept into something highly visible. Makes things like mitochondrial dynamics very clear, for example.',
  },
  {
    id: 'medical',
    title: 'Medical Mode',
    category: 'DLC',
    column: 'dlc',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: [],
    description: 'Focus the project around human medicine.',
    details: 'Content specific to human biology and disease.',
  },
  {
    id: 'microbiome',
    title: 'Microbiome Mode',
    category: 'DLC',
    column: 'dlc',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: [],
    description: 'Focus the project around the human microbiome.',
    details: 'Content specific to human metabolic networks and dysfunctional states that can arise.',
  },
  {
    id: 'cancer',
    title: 'Cancer Mode',
    category: 'DLC',
    column: 'dlc',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: [],
    description: 'Focus the project around cancer.',
    details: 'Content specific to several forms of cancer. Build an understanding of cancer, and community targets for new ideas to try.',
  },
  {
    id: 'developmental',
    title: 'Developmental Biology Mode',
    category: 'DLC',
    column: 'dlc',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: ['differentiation'],
    description: 'A separate mode that introduces developmental biology.',
    details: 'Create structures that change over time. Stem cells create certain types of cell for a limited amount of time, and certain cell types exist only temporarily. The timing and position of these cells can create completely different organisms. Can model heterochrony very well.',
  },
  {
    id: 'sci-fi',
    title: 'Sci Fi Elements',
    category: 'Resource System',
    column: 'mechanics',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: [],
    description: 'In addition to the organic craftables and structures, add some more sci fi content.',
    details: 'Movement upgrades, structures, lasers...',
  },
  /*
  {
    id: 'fatty-acids',
    title: 'Fatty Acid Harvesting',
    category: 'Resource System',
    column: 'mechanics',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: ['primordial-pool'],
    description: 'Collect amphipathic molecules that make membrane construction possible.',
    details: 'This system can quietly introduce hydrophobicity, self-assembly, and membranes through play.',
  },
  
  {
    id: 'hydrophobicity-visor',
    title: 'Hydrophobicity Visor',
    category: 'Player Tool',
    column: 'progression',
    status: 'exploring',
    communitySignal: 'Visually promising',
    dependsOn: ['scanning', 'fatty-acids'],
    description: 'A visual overlay that reveals hydrophilic, neutral, and hydrophobic regions in the world.',
    details: 'This could make molecular properties visible without pausing the game for explanation. The question is whether players use it strategically.',
  },
  {
    id: 'desert',
    title: 'Desert Biome',
    category: 'Biome',
    column: 'biomes',
    status: 'planned',
    communitySignal: 'Strong theme',
    dependsOn: ['vesicles', 'atp-economy'],
    description: 'A biome that encircles the game world with no resources, with strong enemies.',
    details: 'Serves as a natural boundary.',
  },
  */
  {
    id: 'more-cell-types',
    title: 'More Cell Types',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'exploring',
    communitySignal: 'Complex but valuable',
    dependsOn: ['differentiation', 'multicellularity'],
    description: 'Specialized cells beyond root and leaf cells could be introduced.',
    details: 'This goes well with the ability to create one\'s own structures. Defining new cell types (or even letting players define their own custome cell types) could introduce new creativity and new complexity.',
  },
  {
    id: 'silica',
    title: 'Harvest silica from diatoms',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'exploring',
    communitySignal: 'Visually promising',
    dependsOn: [],
    description: 'Diatoms, already in the game, could be a source of silica.',
    details: 'Could be used to make glass for building purposes.',
  },
  {
    id: 'more-cell-types',
    title: 'Tissues',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'exploring',
    communitySignal: 'Complex but valuable',
    dependsOn: ['differentiation', 'multicellularity'],
    description: 'Add lignin and elastin.',
    details: 'These will let the extracellular matrix be either rigid or flexible for more creative builds.',
  },
  {
    id: 'real-cell-flag',
    title: 'Real Cell Flag',
    category: 'Education Layer',
    column: 'education',
    status: 'exploring',
    communitySignal: 'Complex but valuable',
    dependsOn: [],
    description: 'Some sort of visual indication for when a cell is a realistic simulation.',
    details: 'Several proto-cell or cell-like structures exist in the game. For educational purposes, it may be useful to indicate when structures resemble actual cells, instead of utilities in game.',
  },
  /*
  {
    id: 'organelle-logistics',
    title: 'Organelle Logistics',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'exploring',
    communitySignal: 'Complex but valuable',
    dependsOn: ['vesicles', 'hydrophobicity-visor'],
    description: 'Players route cargo between organelle-like structures using vesicles and cytoskeletal tracks.',
    details: 'This maps the factory-game fantasy onto real cell biology: routing, constraints, specialization, bottlenecks, and emergent optimization.',
  },
  {
    id: 'teacher-mode',
    title: 'Teacher Mode',
    category: 'Education Layer',
    column: 'education',
    status: 'exploring',
    communitySignal: 'Later-stage',
    dependsOn: ['primordial-pool', 'scanning'],
    description: 'Optional classroom tools, vocabulary review, and exportable learning moments.',
    details: 'This should not compromise the consumer game. It comes later as an overlay for educators, not as the design center of the core experience.',
  },
  */
  {
    id: 'antibiotics',
    title: 'Additional Antibiotics',
    category: 'Education Layer',
    column: 'education',
    status: 'exploring',
    communitySignal: 'Later-stage',
    dependsOn: ['primordial-pool', 'scanning'],
    description: 'Additional antibiotics would deepen gameplay, enable copmetitive play, and push a player\'s understanding of the systems they build.',
    details: 'Beyond Penicillin, Polymixin B (cell membrane), Streptomycin (ribosome), Rifampicin (RNA polymerase), Bleomycin (DNA), sulfonamides (folate metabolism) could be added.',
  },
  {
    id: 'quiz-gates',
    title: 'Quiz Gates',
    category: 'Rejected Pattern',
    column: 'education',
    status: 'pruned',
    communitySignal: 'Avoid',
    dependsOn: [],
    description: 'Progression blocked by explicit quiz questions.',
    details: 'This is the kind of edtech pattern Atlas Vegrandis should mostly avoid. Understanding should be demonstrated through action and design choices.',
  },
];
