export const roadmapItems = [
  {
    id: 'admin-console',
    title: 'Admin Console',
    category: 'Game Modes',
    column: 'gameModes',
    status: 'planned',
    communitySignal: 'High curiosity',
    dependsOn: [],
    description: 'Enable user to create anything in the game immediately without prerequisites or other restrictions.',
    details: 'Multi-functional mode that enables instant creation, tracking player progress, creating scenarios, and testing of game systems. This mode is intended for educators, parents, and curious players.',
  },
  {
    id: 'multiplayer',
    title: 'Multiplayer',
    category: 'Game Modes',
    column: 'gameModes',
    status: 'planned',
    communitySignal: 'Core',
    dependsOn: [],
    description: 'Co-op and competitive multiplayer modes for players to explore, build, and learn together.',
    details: 'Co-operative play completely reshapes the experience in highly memorable ways. High priority game feature.',
  },
  {
    id: 'communication',
    title: 'Cell-Cell Communication',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'planned',
    communitySignal: 'Core',
    dependsOn: [],
    description: 'Cells can directly communicate. Implement the idea in the game.',
    details: 'Cell-cell communication is a fundamental aspect of biological systems. Implementing this in the game will allow players to interact with and influence each other’s actions.',
  },
  {
    id: 'atp-economy',
    title: 'ATP Economy',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'inProgress',
    communitySignal: 'Needs testing',
    dependsOn: ['scanning'],
    description: 'ATP acts as the global resource that links exploration, upgrades, and biological work.',
    details: 'ATP creates a unifying design grammar: movement, synthesis, repair, transport, and growth all become different expressions of energy management.',
  },
  {
    id: 'vesicles',
    title: 'Vesicle Crafting',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'planned',
    communitySignal: 'Likely key feature',
    dependsOn: ['atp-economy', 'fatty-acids'],
    description: 'Players build simple membrane-bound vesicles as early compartments and transport tools.',
    details: 'Vesicles are the bridge between chemistry and cellular organization. They should feel like a useful survival tool, not a lecture prop.',
  },
  {
    id: 'fatty-acids',
    title: 'Fatty Acid Harvesting',
    category: 'Resource System',
    column: 'mechanics',
    status: 'exploring',
    communitySignal: 'Needs clarity',
    dependsOn: ['primordial-pool'],
    description: 'Collect amphipathic molecules that make membrane construction possible.',
    details: 'This system can quietly introduce hydrophobicity, self-assembly, and membranes through play.',
  },
  {
    id: 'hydrophobicity-visor',
    title: 'Hydrophobicity Visor',
    category: 'Player Tool',
    column: 'progression',
    status: 'exploring',
    communitySignal: 'Visually promising',
    dependsOn: ['scanning', 'fatty-acids'],
    description: 'A visual overlay that reveals hydrophilic, neutral, and hydrophobic regions in the world.',
    details: 'This could make molecular properties visible without pausing the game for explanation. The question is whether players use it strategically.',
  },
  {
    id: 'desert',
    title: 'Desert Biome',
    category: 'Biome',
    column: 'biomes',
    status: 'planned',
    communitySignal: 'Strong theme',
    dependsOn: ['vesicles', 'atp-economy'],
    description: 'A biome that encircles the game world with no resources, with strong enemies.',
    details: 'Serves as a natural boundary.',
  },
  {
    id: 'organelle-logistics',
    title: 'Organelle Logistics',
    category: 'Cell Biology Concepts',
    column: 'biology',
    status: 'planned',
    communitySignal: 'Complex but valuable',
    dependsOn: ['vesicles', 'hydrophobicity-visor'],
    description: 'Players route cargo between organelle-like structures using vesicles and cytoskeletal tracks.',
    details: 'This maps the factory-game fantasy onto real cell biology: routing, constraints, specialization, bottlenecks, and emergent optimization.',
  },
  {
    id: 'teacher-mode',
    title: 'Teacher Mode',
    category: 'Education Layer',
    column: 'education',
    status: 'exploring',
    communitySignal: 'Later-stage',
    dependsOn: ['primordial-pool', 'scanning'],
    description: 'Optional classroom tools, vocabulary review, and exportable learning moments.',
    details: 'This should not compromise the consumer game. It comes later as an overlay for educators, not as the design center of the core experience.',
  },
  {
    id: 'antibiotics',
    title: 'Additional Antibiotics',
    category: 'Education Layer',
    column: 'education',
    status: 'exploring',
    communitySignal: 'Later-stage',
    dependsOn: ['primordial-pool', 'scanning'],
    description: 'Additional antibiotics would deepen gameplay, enable copmetitive play, and push a player\'s understanding of the systems they build.',
    details: 'Beyond Penicillin, Polymixin B (cell membrane), Streptomycin (ribosome), Rifampicin (RNA polymerase), Bleomycin (DNA), sulfonamides (folate metabolism) could be added.',
  },
  {
    id: 'quiz-gates',
    title: 'Quiz Gates',
    category: 'Rejected Pattern',
    column: 'education',
    status: 'pruned',
    communitySignal: 'Avoid',
    dependsOn: [],
    description: 'Progression blocked by explicit quiz questions.',
    details: 'This is the kind of edtech pattern Atlas Vegrandis should mostly avoid. Understanding should be demonstrated through action and design choices.',
  },
];
